FROM python:3.13.2-slim-bookworm
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && apt-get upgrade -y && pip install --upgrade pip && pip install -r requirements.txt && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY src/ ./src
#CMD ["python", "src/simulator.py"]  # Change per file
#EXPOSE 5000
