FROM python:3.13.2-slim-bookworm
# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ ./src
COPY logs/ ./logs  

# Expose FastAPI default port
EXPOSE 8000

# Run the FastAPI app
CMD ["uvicorn", "src.api_server:app", "--host", "0.0.0.0", "--port", "8000"]
